---
version: '3.9'
#==========================================================================
# Sevices
#   This example assumes you have set the various environment variables 
#   such as $DOCKER_DIR.
#==========================================================================
services:
  nutcase:
    image: kronos443/nutcase:latest  # Choose your tag, for example latest_beta or V0.4.0_Beta etc.
    container_name: NUTCase          # Optional, but helpful to identify the container in a list
    restart: unless-stopped          # Options are: "no" always on-failure unless-stopped    
    hostname: NUTCase                # Optional, can help identify activity when tracing traffic
    # user: "$PUID:$PGID"            # Optional
    
    network_mode: host               # Options here are to use host mode or NAT to expose one port only
    # ports:                         # The host option allows the target to be set to 127.0.0.1
    #   - "$NUTEXPORT_PORT:9995"     #   when scraping if the docker host is the same machine as the UPS server.
    
    volumes:                         # The location of the configuration file on the _docker host machine_
      - '$DOCKER_DIR/nutcase:/config'
    environment:
      TZ: $TZ                        # Optional. Ensures the correct time zone appears in the log information 
      LOG_LEVEL: DEBUG               # Optional
    healthcheck:                     # Health checking is optional
      test: wget --spider -q  http://127.0.0.1:$NUTEXPORT_PORT/help
      interval: 3m10s
      timeout: 10s
      retries: 2
      start_period: 30s
    labels:                          # These example labels are only used by watchtower, should you use that to update containers
      - "com.centurylinklabs.watchtower.enable=true"
      #- "com.centurylinklabs.watchtower.enable=false"
      #- "com.centurylinklabs.watchtower.monitor-only=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"
