name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: python-alpine3.18

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker buildx --file Dockerfile --tag kronos443/nutcase:$(date +%s) --platform linux/amd64,linux/arm64/v8,linux/arm/v7 .
